name: build-and-test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3

      - name: Check out Source Code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Format
        run: go fmt .

      - name: Lint & Errcheck
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          skip-go-installation: true

      - name: Test
        run: |
          go test ./...
          go test -race ./...

      - name: Measure Coverage
        run: go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
